
name: docs

on:
  pull_request:
    branches:
      - "main"
      - "master"
  push:
    branches:
      - "main"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: "Doxygen Action"
      uses: mattnotmitt/doxygen-action@1.9.4
      with:
        doxyfile-path: 'liblava\tool\doxygen.conf'
        working-directory: '.'
        enable-latex: true

    - name: GH Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/html/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages

    - name: Generate Table of Contents
      uses: technote-space/toc-generator@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAX_HEADER_LEVEL: 3
        FOLDING: true

    - name: Update Contributors
      uses: akhilmhdh/contributors-readme-action@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        image_size: 100
        columns_per_row: 6

    - name: Download mdsplit
      uses: carlosperate/download-file-action@v1.0.3
      id: download-mdsplit
      with:
        file-url: 'https://github.com/alandefreitas/mdsplit/releases/download/v0.1.1/Executable.Linux.zip'
        file-name: 'mdsplit.zip'
        location: '.'
    - name: Unzip mdsplit
      run: |
        unzip mdsplit.zip
        rm -f mdsplit.zip
        sudo chmod +x mdsplit
        ls
    - name: Generate Documentation Source
      run: ./mdsplit -r alandefreitas/matplotplusplus