name: license check

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  licensecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check License Header
        uses: apache/skywalking-eyes@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Dependencies' License
        uses: apache/skywalking-eyes/dependency@main
