---
name: SuperLinter

on:
  pull_request:
    branches:
      - "main"
      - "master"
  push:
    branches:
      - "main"
      - "master"

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          VALIDATE_PHP: true
          VALIDATE_YAML: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_CPP: true
          VALIDATE_CLANG_FORMAT: true
          VALIDATE_GITLEAKS: true
          VALIDATE_HTML: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}