# spelling.yml is blocked per https://github.com/check-spelling/check-spelling/security/advisories/GHSA-g86g-chm8-7r2p
name: Spell checking
on:
  pull_request_target:
  push:
    branches:
      - "main"
      - "master"
    tags-ignore:
      - "**"

jobs:
  spelling:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: check-spelling/check-spelling@v0.0.19
      id: spelling
      with:
        shortest_word: 2
